"""Cortex build script — produces provider-specific artifacts and a release tarball.

Usage:
    python build.py --tag v1.0.0 [--dist ./dist]

iEVO.md is rendered ONCE (provider-agnostic) → dist/iEVO.md.
For each provider target (claude, codex):
    - Renders provider-specific artifacts from src/
    - Writes to dist/<provider>/
    - Creates dist/cortex-<tag>.tar.gz with iEVO.md at root + provider directories

BREAKING CHANGE (REQ-004): iEVO.md moved from dist/<provider>/iEVO.md to dist/iEVO.md.

v1 placeholder behavior:
    - dist/iEVO.md: kernel (provider-agnostic)
    - claude/: one placeholder agent .md
    - codex/: BUILD_TARGET.md (format TBD per IDEA-005)
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

import jinja2
from jinja2 import Environment, FileSystemLoader, StrictUndefined

CORTEX_ROOT = Path(__file__).parent
IEVO_MD_TEMPLATE = CORTEX_ROOT / "src" / "kernel" / "iEVO.md.j2"


def render_template(
    template_path: Path, context: dict[str, str], loader_root: Path | None = None
) -> str:
    """Render a Jinja2 template file with the given context variables.

    Args:
        template_path: Absolute path to the .j2 template file.
        context: Variables to pass to the template.
        loader_root: Root directory for the Jinja2 FileSystemLoader. Defaults to
            ``template_path.parent.parent`` when not provided.

    Returns:
        Rendered string content.

    Raises:
        FileNotFoundError: If the template file does not exist.
        jinja2.UndefinedError: If the template references a variable not in context.
    """
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    if loader_root is None:
        loader_root = template_path.parent.parent
    relative = template_path.relative_to(loader_root)

    env = Environment(
        loader=FileSystemLoader(str(loader_root)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        autoescape=False,
    )
    template = env.get_template(str(relative))
    return template.render(**context)


CLAUDE_AGENT_MD = """\
---
name: spec-writer
description: >
  Converts features into atomic, testable requirements. Use PROACTIVELY for new features.
model: sonnet
---

# Spec Writer

> Auto-generated by Cortex v1 build pipeline. Source: ievo-ai/cortex

Converts user stories and feature descriptions into formal REQ files with acceptance criteria.
"""

# Placeholder content for codex/ target (v1)
CODEX_BUILD_TARGET_MD = """\
# Codex Build Target

> Placeholder — Codex agent format is under research (IDEA-005).

This directory will contain OpenAI Codex-compatible agent configuration files
once the format is finalized.

See: https://github.com/ievo-ai/cortex/issues (IDEA-005)
"""


def validate_links(dist_dir: Path) -> None:
    """Validate Markdown links in dist_dir using lychee.

    Runs lychee with --offline (skip external URLs), --include-fragments (anchor
    checking — mandatory for AC-2 and AC-4), and --no-progress (CI-friendly output).

    If lychee is not on PATH, prints a warning to stderr and returns without error —
    allowing local development without lychee installed. CI is the authoritative gate.

    If lychee exits non-zero (exit 2 = broken links, exit 1 = runtime error), prints
    lychee's output and calls sys.exit() with the same return code.

    # TODO(IDEA-011): orphaned anchor detection — headings never referenced

    Args:
        dist_dir: Path to the rendered output directory (e.g. dist/).
    """
    lychee_bin = shutil.which("lychee")
    if lychee_bin is None:
        print(
            "Warning: lychee not found on PATH — skipping link validation. "
            "Install lychee to validate Markdown links locally.",
            file=sys.stderr,
        )
        return

    result = subprocess.run(
        ["lychee", "--offline", "--include-fragments", "--no-progress", str(dist_dir)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        if result.stdout:
            print(result.stdout, file=sys.stderr)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)


def render_ievo_md(dist_dir: Path, tag: str) -> None:
    """Render iEVO.md once (provider-agnostic) → dist_dir/iEVO.md."""
    rendered = render_template(
        IEVO_MD_TEMPLATE,
        {"cortex_version": tag},
        CORTEX_ROOT / "src",
    )
    (dist_dir / "iEVO.md").write_text(rendered)


def build_claude_target(claude_dir: Path, tag: str) -> None:
    """Render claude/ provider artifacts."""
    claude_dir.mkdir(parents=True, exist_ok=True)

    agents_dir = claude_dir / "agents"
    agents_dir.mkdir(exist_ok=True)
    (agents_dir / "spec-writer.md").write_text(CLAUDE_AGENT_MD)


def build_codex_target(codex_dir: Path, tag: str) -> None:
    """Render codex/ provider artifacts."""
    codex_dir.mkdir(parents=True, exist_ok=True)

    (codex_dir / "BUILD_TARGET.md").write_text(CODEX_BUILD_TARGET_MD)


def create_tarball(dist_dir: Path, tag: str) -> Path:
    """Create cortex-<tag>.tar.gz with iEVO.md at root + provider directories."""
    tarball_path = dist_dir / f"cortex-{tag}.tar.gz"

    with tarfile.open(tarball_path, "w:gz") as tf:
        # Add iEVO.md at tarball root (provider-agnostic)
        ievo_md = dist_dir / "iEVO.md"
        if ievo_md.exists():
            tf.add(ievo_md, arcname="iEVO.md")

        # Add provider-specific directories
        for provider in ("claude", "codex"):
            provider_dir = dist_dir / provider
            if provider_dir.exists():
                for file_path in sorted(provider_dir.rglob("*")):
                    if file_path.is_file():
                        arcname = str(file_path.relative_to(dist_dir))
                        tf.add(file_path, arcname=arcname)

    return tarball_path


def build(tag: str, dist_dir: Path) -> Path:
    """Build all provider targets and create release tarball.

    Returns the path to the created tarball.
    """
    # Clean and recreate provider dirs for idempotency
    for provider in ("claude", "codex"):
        provider_dir = dist_dir / provider
        if provider_dir.exists():
            shutil.rmtree(provider_dir)

    dist_dir.mkdir(parents=True, exist_ok=True)

    build_claude_target(dist_dir / "claude", tag)
    build_codex_target(dist_dir / "codex", tag)

    # Render iEVO.md once — provider-agnostic (REQ-004)
    render_ievo_md(dist_dir, tag)

    validate_links(dist_dir)

    return create_tarball(dist_dir, tag)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Cortex release artifacts.")
    parser.add_argument("--tag", required=True, help="Release tag (e.g. v1.0.0)")
    parser.add_argument(
        "--dist",
        default=str(CORTEX_ROOT / "dist"),
        help="Output directory (default: ./dist)",
    )
    args = parser.parse_args()

    dist_dir = Path(args.dist)
    try:
        tarball = build(tag=args.tag, dist_dir=dist_dir)
    except FileNotFoundError as exc:
        print(f"Error: template file not found — {exc}", file=sys.stderr)
        sys.exit(1)
    except jinja2.UndefinedError as exc:
        print(f"Error: undefined template variable — {exc}", file=sys.stderr)
        sys.exit(1)
    print(f"Built: {tarball}")


if __name__ == "__main__":
    main()
