"""Cortex build script — produces provider-specific artifacts and a release tarball.

Usage:
    python build.py --tag v1.0.0 [--dist ./dist]

For each provider target (claude, codex):
    - Renders provider-specific output files from src/
    - Writes to dist/<provider>/
    - Creates dist/cortex-<tag>.tar.gz containing both provider directories

v1 placeholder behavior:
    - claude/: iEVO.md (kernel) + one placeholder agent .md
    - codex/: BUILD_TARGET.md (format TBD per IDEA-005)
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tarfile
from pathlib import Path

import jinja2
from jinja2 import Environment, FileSystemLoader, StrictUndefined

CORTEX_ROOT = Path(__file__).parent


def render_template(template_path: Path, context: dict[str, str]) -> str:
    """Render a Jinja2 template file with the given context variables.

    Args:
        template_path: Absolute path to the .j2 template file.
        context: Variables to pass to the template.

    Returns:
        Rendered string content.

    Raises:
        FileNotFoundError: If the template file does not exist.
        jinja2.UndefinedError: If the template references a variable not in context.
    """
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    loader_root = template_path.parent.parent  # e.g. src/ when template is src/kernel/foo.j2
    relative = template_path.relative_to(loader_root)

    env = Environment(
        loader=FileSystemLoader(str(loader_root)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        autoescape=False,
    )
    template = env.get_template(str(relative))
    return template.render(**context)


# Placeholder content for claude/ target (v1)
CLAUDE_IEVO_MD = """\
# iEVO Kernel

> This file is auto-generated by the Cortex build pipeline.
> Source: ievo-ai/cortex — see src/kernel/iEVO.yaml

iEvo pipeline conventions. Read this file at session start.

## Pipeline

See full conventions in the iEvo CLI documentation.
"""

CLAUDE_AGENT_MD = """\
---
name: spec-writer
description: >
  Converts features into atomic, testable requirements. Use PROACTIVELY for new features.
model: sonnet
---

# Spec Writer

> Auto-generated by Cortex v1 build pipeline. Source: ievo-ai/cortex

Converts user stories and feature descriptions into formal REQ files with acceptance criteria.
"""

# Placeholder content for codex/ target (v1)
CODEX_BUILD_TARGET_MD = """\
# Codex Build Target

> Placeholder — Codex agent format is under research (IDEA-005).

This directory will contain OpenAI Codex-compatible agent configuration files
once the format is finalized.

See: https://github.com/ievo-ai/cortex/issues (IDEA-005)
"""


def build_claude_target(claude_dir: Path) -> None:
    """Render claude/ provider artifacts."""
    claude_dir.mkdir(parents=True, exist_ok=True)

    (claude_dir / "iEVO.md").write_text(CLAUDE_IEVO_MD)

    agents_dir = claude_dir / "agents"
    agents_dir.mkdir(exist_ok=True)
    (agents_dir / "spec-writer.md").write_text(CLAUDE_AGENT_MD)


def build_codex_target(codex_dir: Path) -> None:
    """Render codex/ provider artifacts (placeholder for v1)."""
    codex_dir.mkdir(parents=True, exist_ok=True)
    (codex_dir / "BUILD_TARGET.md").write_text(CODEX_BUILD_TARGET_MD)


def create_tarball(dist_dir: Path, tag: str) -> Path:
    """Create cortex-<tag>.tar.gz containing claude/ and codex/ from dist_dir."""
    tarball_path = dist_dir / f"cortex-{tag}.tar.gz"

    with tarfile.open(tarball_path, "w:gz") as tf:
        for provider in ("claude", "codex"):
            provider_dir = dist_dir / provider
            if provider_dir.exists():
                for file_path in sorted(provider_dir.rglob("*")):
                    if file_path.is_file():
                        arcname = str(file_path.relative_to(dist_dir))
                        tf.add(file_path, arcname=arcname)

    return tarball_path


def build(tag: str, dist_dir: Path) -> Path:
    """Build all provider targets and create release tarball.

    Returns the path to the created tarball.
    """
    # Clean and recreate provider dirs for idempotency
    for provider in ("claude", "codex"):
        provider_dir = dist_dir / provider
        if provider_dir.exists():
            shutil.rmtree(provider_dir)

    dist_dir.mkdir(parents=True, exist_ok=True)

    build_claude_target(dist_dir / "claude")
    build_codex_target(dist_dir / "codex")

    return create_tarball(dist_dir, tag)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Cortex release artifacts.")
    parser.add_argument("--tag", required=True, help="Release tag (e.g. v1.0.0)")
    parser.add_argument(
        "--dist",
        default=str(CORTEX_ROOT / "dist"),
        help="Output directory (default: ./dist)",
    )
    args = parser.parse_args()

    dist_dir = Path(args.dist)
    tarball = build(tag=args.tag, dist_dir=dist_dir)
    print(f"Built: {tarball}")


if __name__ == "__main__":
    main()
